
query RushingsConnection ($first: Int, $last: Int, $sortBy: String, $sortDesc: Boolean, $nameFilter: String, $after: String, $before: String) {
 rushings(first: $first, last: $last, sortBy: $sortBy, sortDesc: $sortDesc, nameFilter: $nameFilter, after: $after, before: $before){
    edges{
      cursor
      node{
        id
        playerName
        team
        position
        attempts
        attemptsPerGameAvg
        yards
        yardsPerGameAvg
        yardsPerAttemptAvg
        touchdowns
        longuest
        firstDowns
        firstDownsPct
        twentyPlus
        fourtyPlus
        fumbles
      }
    }
    pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
  }
}